version: '3'

services:
  apt-cacher-ng:
    image: apt-cacher-ng
    container_name: apt-cacher-ng-container
    ports:
      - "3142:3142"
    volumes:
      - apt-cacher-ng-cache:/var/cache/apt-cacher-ng

volumes:
  apt-cacher-ng-cache: